name: First Workflow
on: workflow_dispatch                   # for when this workflow will begin, waits for the user to manually trigger the workflow
jobs:                                   # define a job/jobs (jobs reserved)
  first-job:                            # first job on the workflow - can be named anything
    runs-on: ubuntu-latest              # reserved runner
    steps:                              # define steps
      - name: Print greeting            # name of the step
        run: echo "Hello World!"        # command that will be run on the command line
      - name: Print goodbye
        run: echo "Done - bye!"
        
