name: Matrix Demo

on: 
  push: 
    branches: [ main ]

jobs: 
  build: 
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ ubuntu-latest, windows-latest ]
        # allows you to add new stand alone combinations
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest

    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code 
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: |
          cd "06 Execution Flow/Project" && npm ci

      - name: Build Project
        run: |
          cd "06 Execution Flow/Project" && npm run build