name: Deploy website

on:
  push:
    branches: [ gh-artifacts ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd 04\ Artifacts\ \&\ Outputs/01\ Starting\ Project 
          npm ci
      - name: Lint code
        run: |
          cd 04\ Artifacts\ \&\ Outputs/01\ Starting\ Project
          npm run lint
      - name: Test code
        run: |
          cd 04\ Artifacts\ \&\ Outputs/01\ Starting\ Project
          npm run test
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cd 04\ Artifacts\ \&\ Outputs/01\ Starting\ Project
          npm ci
      - name: Build website
        run: |
          cd 04\ Artifacts\ \&\ Outputs/01\ Starting\ Project
          npm run build
      - name: Upload artifacts                                  # to upload files onto the github cli
        uses: actions/upload-artifact@v4
        with:
          name: dist-files                                      # identifier/name of the file once uploaded
          path: 04\ Artifacts\ \&\ Outputs/02\ Extra\ Files     # file path 
          #  path: |
          #    dist
          #   package.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files                                      # use the same identifier as uploaded
      - name: Output contents
        run: ls                                                 # list contents of artifact
      - name: Deploy
        run: echo "Deploying..."
