name: Deployment (Container)

on:
  push:
    branches:
    #  - main
      - gh-containers

env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo

jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    # container: 
    #   image: node:16                                          # https://hub.docker.com/_/node
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      #MONGODB_CLUSTER_ADDRESS: mongodb                       # uses services label to establish connection
      MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017                # used when not ruuning on a container
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      PORT: 8080
    # container service used only for testing                 # https://hub.docker.com/_/mongo
    services:
      mangodb:
        image: mongo
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd "07 Containers/Project" && npm ci
      - name: Run server
        run: |
          cd "07 Containers/Project" 
          npm start & npx wait-on http://127.0.0.1:$PORT          # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: |
          cd "07 Containers/Project" && npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
