name: Linting Workflow

on: push

jobs:
    run-linting:
        runs-on: ubuntu-latest

        steps: 
            - name:  Get code
              uses: actions/checkout@v4

            - name: Install NodeJS
              uses: actions/setup-node@v4.1.0
              with:
                node-version: 18

            - name: Lint action
              uses: wearerequired/lint-action@v2.3.0
              with:
                eslint: true
                prettier: true

            - name: Install dependencies
              run: |
                cd 04\ Practice\ Project\ \(Start\)  && npm install
 
            
            - name: Run tests
              run: |
                cd 04\ Practice\ Project\ \(Start\) && npm test

            - name: Run build
              run: |
                cd 04\ Practice\ Project\ \(Start\) && npm build

