name: Matrix Demo

on: 
  push: 
    branches: [ gh-exec-flow ]

jobs: 
  build: 
    strategy:
      matrix:
        node-version: [12, 14, 16]
        operating-system: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code 
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: |
          cd "06 Execution Flow/Project" && npm ci

      - name: Build Project
        run: |
          cd "06 Execution Flow/Project" && npm run build